# Linear Algebra NOTES AND DEMOS

In [2]:
import numpy as np
from numpy.polynomial.polynomial import Polynomial
import matplotlib.pyplot as plt
import random
import math
import turtle
import secrets
import time
from sympy.ntheory import factorint

In [4]:
    A = np.array([
    [2, 3, 7],
    [8, 9, 1]
    ])
    B = np.array([
    [1, -3, 0],
    [2, -4, 1]
    ])
    print(A + B)
    print(2 * A)
    print(A * B) # Element-wise multiplication
    print(A.dot(B)) # Error: shapes not aligned
    print(A.dot(B.T)) # Matrix multiplication

[[ 3  0  7]
 [10  5  2]]
[[ 4  6 14]
 [16 18  2]]
[[  2  -9   0]
 [ 16 -36   1]]


ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)